# Generated by Django 4.2.11 on 2026-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzil',
            name='image',
            field=models.ImageField(default=None, upload_to='manzillar/'),
            preserve_default=False,
        ),
    ]
