# Generated by Django 4.2.11 on 2026-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzil', '0002_manzil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manzil/'),
        ),
    ]
